pipeline {
    
    agent any 
    
    environment {
        IMAGE_NAME = "aditya3k4/django-todo"
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git branch: 'main',
                url: 'git@github.com:adityasingh307/Jenkins-Zero-To-Hero.git'
            }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t aditya3k4/django-todo:${BUILD_NUMBER} python-jenkins-argocd-k8s
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push aditya3k4/django-todo:${BUILD_NUMBER}
                    '''
                }
            }
        }
        

        stage('Update Deployment Manifest') {
            steps {
                sh '''
                sed -i "s|image: .*|image: ${IMAGE_NAME}:${IMAGE_TAG}|" \
                python-jenkins-argocd-k8s/deploy/deployment.yaml
                '''
            }
        }
        
         stage('Commit & Push Manifest') {
            steps {
                sh '''
                git config user.email "jenkins@local"
                git config user.name "jenkins"

                git add python-jenkins-argocd-k8s/deploy/deployment.yaml
                git commit -m "update image to ${IMAGE_TAG}"
                git push origin main
                '''
            }
        }
    }
}
